commit 403076375 on 20211116

diff --git a/termux-api/cams b/termux-api/cams
--- a/termux-api/cams
+++ b/termux-api/cams
@@ -51,9 +51,21 @@ trap _TRPET_ EXIT
 trap _TRPSIG_ HUP INT TERM
 trap _TRPQ_ QUIT
 
+# show help
 [[ -n "${1:-}" ]] && { [[ "${1//-}" = [\/]* ]] || [[ "${1//-}" = [?]* ]] || [[ "${1//-}" = [Hh]* ]] ; } && { printf '\e[1;32m%s\n' "Help for '${0##*/}':" && TSFILE="($(grep '##\ ' "$0"))" && printf '\e[0;32m%s\e[1;32m\n%s\n' "$(for HL in "${TSFILE[@]}" ; do cut -d\) -f1 <<< "${HL//###/	}" | cut -f 2 ; done )" "Help for '${0##*/}': DONE" ; exit ; }
-[[ -n "${1:-}" ]] && { [[ "${1//-}" = [Pp]* ]] && POCKET=0 && CAMID=2 && echo pocket || CAMID=${1:-2} ; }
-[[ -z "${1:-}" ]] && CAMID=2 ### [1] default 2:  One camera 0 1 2 3 4 5 6 7 id,
+# use pocket mode
+[[ -n "${1:-}" ]] && { [[ "${1//-}" = [Pp]* ]] && POCKET=0 && CAMID=2 && echo using pocket mode || CAMID=${1:-2} ; }
+_DEFCAM_ () { # set default camera id
+for CAMID in $(termux-camera-info | grep -w "id" | cut -d"\"" -f 4)
+do
+if [ "$CAMID" == 2 ]
+then
+CAMID=2 
+break
+fi
+done
+}
+[[ -z "${1:-}" ]] && _DEFCAM_ ### [1] default 2:  One camera 0 1 2 3 4 5 6 7 id,
 FRAMECTOT=${2:-11} ### [2] default 11:  Total frame count + 1,
 FRAMERATE=${3:-1} ### [3] default 1:  Video 0.5 1 2 4 8 16 32 frames per second rendered in the mpg file,
 THRESHOLDSET=${4:-256} ### [4] default 256:  Byte difference 64 128 256 512 1024 2048 4096 8192 16384 32768 65536 between last two picture frames taken;  Can be used for motion detection.  The greater the number, the lesser the sensitivity.  Camera resolution also affects this argument,
@@ -122,8 +134,8 @@ fi
 _MAKEDIRS_ () {
 CAMD="camid$CAMID"
 [ -e "output/$CAMD/$CAMD$TIMESTAMP" ] || { printf '\e[0;36m%s' "IM mkdir -p output/$CAMD/$CAMD$TIMESTAMP: " && mkdir -p output/"$CAMD/$CAMD$TIMESTAMP" && printf '\e[0;32m%s\n' "DONE"; }
-[ -e output/gifs/"$CAMD" ] || { printf '\e[0;36m%s' "IM mkdir -p output/gifs/$CAMD: " && mkdir -p output/gifs/"$CAMD" && printf '\e[0;32m%s\n' "DONE"; }
-[ -e output/webms/"$CAMD" ] || { printf '\e[0;36m%s' "IM mkdir -p output/webms/$CAMD: " && mkdir -p output/webms/"$CAMD" && printf '\e[0;32m%s\n' "DONE"; }
+[ -e output/"$CAMD"/gifs ] || { printf '\e[0;36m%s' "IM mkdir -p output/$CAMD/gifs: " && mkdir -p output/"$CAMD"/gifs && printf '\e[0;32m%s\n' "DONE"; }
+[ -e output/"$CAMD"/mp4s ] || { printf '\e[0;36m%s' "IM mkdir -p output/$CAMD/mp4s: " && mkdir -p output/"$CAMD/mp4s" && printf '\e[0;32m%s\n' "DONE"; }
 printf '\e[0;36m%s' "IM cd output/$CAMD/$CAMD$TIMESTAMP: " && cd output/"$CAMD/$CAMD$TIMESTAMP" && printf '\e[0;32m%s\n' "DONE"
 }
 _MAGICKCK_ () {
@@ -155,13 +167,14 @@ fi
 fi
 }
 _MECONVERT_ () {
-printf '\e[0;36m%s\e[0m\n' "IM making camid$CAMID.$TIMESTAMP.gif: This job will complete in the background..." && nice -n 20 convert -delay "$((FRAMERATE * 100))" -loop 0 "$CAMD."*.jpg "$CAMD.$TIMESTAMP".gif && { ls -al "$CAMD.$TIMESTAMP".gif && printf '\e[0;32m%s\e[0m\n' "IM making camid$CAMID.$TIMESTAMP.gif: DONE" ; } || printf '\e[1;31m%s\e[0m\n' "EM creating camid$CAMID.$TIMESTAMP.gif: ERROR"
-printf '\e[0;36m%s' "IM mv camid$CAMID.$TIMESTAMP.gif ../../gifs/$CAMD: " && mv "$CAMD.$TIMESTAMP".gif ../../gifs/$CAMD && printf '\e[0;32m%s\e[0m\n' "DONE"
+printf '\e[0;36m%s\e[0m\n' "IM making camid$CAMID.$TIMESTAMP.gif: This job will complete in the background..." && nice -n 20 ffmpeg -i "$CAMD."%04d.jpg camid"$CAMD.$TIMESTAMP".gif && { ls -al camid"$CAMD.$TIMESTAMP".gif && printf '\e[0;32m%s\e[0m\n' "IM making camid$CAMID.$TIMESTAMP.gif: DONE" ; } || printf '\e[1;31m%s\e[0m\n' "EM creating camid$CAMID.$TIMESTAMP.gif: ERROR"
+printf '\e[0;36m%s' "IM mv camid$CAMID.$TIMESTAMP.gif ../gifs/: " && mv camid"$CAMD.$TIMESTAMP".gif ../gifs/ && printf '\e[0;32m%s\e[0m\n' "DONE"
 }
 _MEFFMPEG_ () {
+#ffmpeg -i "$CAMD."%04d.jpg -c:v libx264 -preset veryslow -crf 0 output.mkv
 # To start at frame 20 and finish at frame 420: ffmpeg -start_number 20 -i filename%04d.jpg -vframes 400 video.webm
-printf '\e[0;36m%s\e[0m\n' "IM making camid$CAMID.$TIMESTAMP.webm: This job will complete in the background..." && nice -n 20 ffmpeg -framerate "$FRAMERATE" -i "$CAMD."%04d.jpg -movflags +faststart -c:v libvpx-vp9 -g 25 "$CAMD.$TIMESTAMP".webm && { ls -al "$CAMD.$TIMESTAMP".webm && printf '\e[0;32m%s\e[0m\n' "IM making camid$CAMID.$TIMESTAMP.webm: DONE" ; } || printf '\e[1;31m%s\e[0m\n' "EM creating camid$CAMID.$TIMESTAMP.webm: ERROR"
-printf '\e[0;36m%s' "IM mv camid$CAMID.$TIMESTAMP.webm ../../webm/$CAMD : " && mv "$CAMD.$TIMESTAMP".webm ../../webms/$CAMD && printf '\e[0;32m%s\e[0m\n' "DONE"
+printf '\e[0;36m%s\e[0m\n' "IM making camid$CAMID.$TIMESTAMP.mp4: This job will complete in the background..." && nice -n 20 ffmpeg -framerate "$FRAMERATE" -i "$CAMD."%04d.jpg  -c:v libx264 -preset veryslow -crf 0 -g 1 camid"$CAMD.$TIMESTAMP".mp4 && { ls -al camid"$CAMD.$TIMESTAMP".mp4 && printf '\e[0;32m%s\e[0m\n' "IM making camid$CAMID.$TIMESTAMP.mp4: DONE" ; } || printf '\e[1;31m%s\e[0m\n' "EM creating camid$CAMID.$TIMESTAMP.mp4: ERROR"
+printf '\e[0;36m%s' "IM mv camid$CAMID.$TIMESTAMP.mp4 ../mp4s/: " && mv camid"$CAMD.$TIMESTAMP".mp4 ../mp4s/ && printf '\e[0;32m%s\e[0m\n' "DONE"
 }
 printf '\e[0;34m%s\e[1;36m%s\e[0;34m%s' "Starting command " "termux-wake-lock" ": "
 am startservice --user 0 -a com.termux.service_wake_lock com.termux/com.termux.app.TermuxService 1>/dev/null && printf '\e[0;32m%s\n\e[0;34m%s\e[1;36m%s\e[0;34m%s\n' "DONE" "Command " "termux-wake-unlock" " stops the wake lock." || printf '\e[0;33m%s\e[0m\n' "UTP am startservice: Continuing..."
